### ISSUE TITLE
unknown builtin types nonempty_binary/0 and nonempty_bitstring/0

### ISSUE THREAD

**Issue by sg2342** [WhatsApp/eqwalizer#26]
Erlang OTP-24.0 introduced new internal types `nonempty_binary()` and `nonempty_bitstring()` [in this PR](https://github.com/erlang/otp/pull/4762).

when eqwalizer is confronted with erlang specs that contain these, it crashes
```
Exception in thread "main" java.lang.AssertionError: assertion failed: unknown builtin type nonempty_binary/0
	at scala.Predef$.assert(Predef.scala:279)
	at com.whatsapp.eqwalizer.ast.ConvertAst.convertType(ConvertAst.scala:306)
...
```
or
```
Exception in thread "main" java.lang.AssertionError: assertion failed: unknown builtin type nonempty_bitstring/0
	at scala.Predef$.assert(Predef.scala:279)
	at com.whatsapp.eqwalizer.ast.ConvertAst.convertType(ConvertAst.scala:306)
...
```

**Comment by VLanvin** [comment]
Looks like we missed two builtin types indeed. Thanks for finding them.

This will be fixed ASAP in the next release.

**Comment by ilya-klyuchnikov** [comment]
This is fixed in today's release: https://github.com/WhatsApp/eqwalizer/releases/tag/v0.16.27
